services:
  database:
    image: postgres:18
    container_name: database
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  user-database:
      image: postgres:18
      container_name: user-database
      environment:
        POSTGRES_DB: ${POSTGRES_USER_DB}
        POSTGRES_USER: ${POSTGRES_USER_USER}
        POSTGRES_PASSWORD: ${POSTGRES_USER_PASSWORD}
      ports:
        - "5433:5432"
      volumes:
        - user-database:/var/lib/postgresql
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER_USER} -d ${POSTGRES_USER_DB}"]
        interval: 5s
        timeout: 5s
        retries: 5

  driver-database:
      image: postgres:18
      container_name: driver-database
      environment:
        POSTGRES_DB: ${POSTGRES_DRIVER_DB}
        POSTGRES_USER: ${POSTGRES_DRIVER_USER}
        POSTGRES_PASSWORD: ${POSTGRES_DRIVER_PASSWORD}
      ports:
        - "5434:5432"
      volumes:
        - driver-database:/var/lib/postgresql
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_DRIVER_USER} -d ${POSTGRES_DRIVER_DB}"]
        interval: 5s
        timeout: 5s
        retries: 5

  cache:
    image: redis:8.6
    container_name: cache
    ports:
      - "6379:6379"
    volumes:
      - cache:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5

  auth-service:
    image: rideflow/auth-service:latest
    container_name: auth-service
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      NODE_ENV: production
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}
      JWT_ACCESS_SECRET: ${JWT_ACCESS_SECRET}
      JWT_ACCESS_EXPIRES_IN: ${JWT_ACCESS_EXPIRES_IN}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      JWT_REFRESH_EXPIRES_IN: ${JWT_REFRESH_EXPIRES_IN}
    depends_on:
      database:
        condition: service_healthy
      cache:
        condition: service_healthy
    restart: unless-stopped


  user-service:
    image: rideflow/user-service:latest
    container_name: user-service
    ports:
      - "3001:3001"
    environment:
      PORT: 3001
      NODE_ENV: production
      DATABASE_URL: postgresql://${POSTGRES_USER_USER}:${POSTGRES_USER_PASSWORD}@user-database:5432/${POSTGRES_USER_DB}
      JWT_ACCESS_SECRET: ${JWT_ACCESS_SECRET}
    depends_on:
      user-database:
        condition: service_healthy
      cache:
        condition: service_healthy
    restart: unless-stopped

  driver-service:
    image: rideflow/driver-service:latest
    container_name: driver-service
    ports:
      - "3002:3002"
    environment:
      PORT: 3002
      NODE_ENV: production
      DATABASE_URL: postgresql://${POSTGRES_DRIVER_USER}:${POSTGRES_DRIVER_PASSWORD}@driver-database:5432/${POSTGRES_DRIVER_DB}
      JWT_ACCESS_SECRET: ${JWT_ACCESS_SECRET}
    depends_on:
      driver-database:
        condition: service_healthy
      cache:
        condition: service_healthy
    restart: unless-stopped

volumes:
  database:
  user-database:
  driver-database:
  cache:
